import requests
import time
urls = [
    'https://xuongmocdct.com.vn/noi-that-van-phong/ban-lam-viec-mau-xam-bac-blvxmdct10',
    'https://xuongmocdct.com.vn/noi-that-van-phong/ghe-van-phong-cong-thai-hoc-mau-hong-gvpxmdct03',
    'https://xuongmocdct.com.vn/noi-that-van-phong/ban-lam-viec-phong-cach-vintage-blvxmdct05',
    'https://xuongmocdct.com.vn/noi-that-van-phong/ban-lam-viec-chat-lieu-sang-trong-blvxmdct01',
    'https://xuongmocdct.com.vn/noi-that-van-phong/ban-may-tinh-bang-go-blvxmdct02',
    'https://xuongmocdct.com.vn/noi-that-van-phong/ban-lam-viec-go-cong-nghiep-blvxmdct03',
    'https://xuongmocdct.com.vn/noi-that-van-phong/ban-lam-viec-hinh-chu-l-blvxmdct04',
    'https://xuongmocdct.com.vn/noi-that-phong-khach/sofa-thu-gian-hoan-hao-cho-phong-khach-gfdct06',
    'https://xuongmocdct.com.vn/noi-that-phong-ngu/ban-trang-diem-venice-go-tu-nhien-ket-hop-guong-btfdct03',
    'https://xuongmocdct.com.vn/noi-that-phong-ngu/ban-trang-diem-diel-ket-hop-guong-btfdct04',
    'https://xuongmocdct.com.vn/noi-that-phong-bep/tu-bep-go-cong-nghiep-phoi-mau-trang-xam-an-tuong-tbdct09',
    'https://xuongmocdct.com.vn/noi-that-phong-bep/ban-an-go-liverpool-4-ghe-bfgdct03',
    'https://xuongmocdct.com.vn/noi-that-phong-bep/ban-an-ceramic-winston-8-ghe-bfdct05',
    'https://xuongmocdct.com.vn/noi-that-phong-bep/ghe-an-chan-sat-georgia-gpsdct03',
    'https://xuongmocdct.com.vn/noi-that-phong-bep/ghe-an-chan-sat-cao-cap-winston-gpsdct05',
    'https://xuongmocdct.com.vn/noi-that-phong-bep/ban-an-go-value-4-ghe-bfgdct04',
    'https://xuongmocdct.com.vn/noi-that-phong-bep/ghe-an-go-cao-su-value-gpgdct04',
    'https://xuongmocdct.com.vn/noi-that-phong-bep/ghe-an-go-houston-gpgdct05',
    'https://xuongmocdct.com.vn/noi-that-phong-bep/ghe-an-go-ket-hop-pvc-gpgdct06',
    'https://xuongmocdct.com.vn/noi-that-phong-bep/ghe-an-xoay-florin-gpdct01',
    'https://xuongmocdct.com.vn/noi-that-phong-bep/ghe-an-go-cao-su-liverpool-gpgdct03',
    'https://xuongmocdct.com.vn/noi-that-phong-bep/ban-an-firenze-2-ghe-bfdct05',
    'https://xuongmocdct.com.vn/noi-that-phong-bep/ban-an-24-ghe-mo-rong-picnic-bfdct01',
    'https://xuongmocdct.com.vn/noi-that-phong-bep/ban-an-2-ghe-picnic-chan-tru-bfdct02',
    'https://xuongmocdct.com.vn/noi-that-phong-bep/bo-ban-ghe-an-stdct13-6-ghe-sang-trong-va-lich-lam',
    'https://xuongmocdct.com.vn/noi-that-phong-ngu/giuong-ngu-go-bddct09-phong-cach-rustic-tone-mau-nau-tram',
    'https://xuongmocdct.com.vn/noi-that-phong-ngu/tu-ao-canh-lua-go-cong-nghiep-thiet-ke-thong-minh',
    'https://xuongmocdct.com.vn/noi-that-phong-ngu/tu-ao-wddct06-canh-mo-mau-trang-chat-lieu-go-sang-trong',
    'https://xuongmocdct.com.vn/noi-that-phong-ngu/don-ban-phan-thiet-ke-hinh-oval-voi-2-chan-tru-chac-chan',
    'https://xuongmocdct.com.vn/noi-that-phong-ngu/ghe-don-phong-ngu-khung-chan-sat-dem-ngoi-em-ai',
    'https://xuongmocdct.com.vn/noi-that-phong-ngu/ban-phan-treo-tuong-tone-mau-trang-thiet-ke-hien-dai',
    'https://xuongmocdct.com.vn/noi-that-phong-ngu/don-ban-phan-phong-ngu-hinh-tru-thiet-ke-moi-la',
    'https://xuongmocdct.com.vn/noi-that-van-phong/ban-lam-viec-nho-xinh-kem-gia-sach',
    'https://xuongmocdct.com.vn/noi-that-phong-ngu/tap-dau-giuong-btdct09-mau-trang-phong-cach-tan-co',
    'https://xuongmocdct.com.vn/noi-that-phong-ngu/giuong-ngu-boc-ni-bddct07',
    'https://xuongmocdct.com.vn/noi-that-phong-ngu/tap-dau-giuong-btdct08',
    'https://xuongmocdct.com.vn/noi-that-phong-bep/bo-ban-ghe-an-stdct11-04',
    'https://xuongmocdct.com.vn/noi-that-phong-bep/bo-ban-ghe-an-stdct12-04',
    'https://xuongmocdct.com.vn/noi-that-phong-ngu/giuong-ngu-go-bddct06',
    'https://xuongmocdct.com.vn/noi-that-phong-ngu/giuong-ngu-boc-ni-bdct08',
    'https://xuongmocdct.com.vn/noi-that-phong-ngu/tap-dau-giuong-btdct05',
    'https://xuongmocdct.com.vn/noi-that-phong-ngu/tap-dau-giuong-btdct06',
    'https://xuongmocdct.com.vn/noi-that-phong-ngu/tap-dau-giuong-btdct03',
    'https://xuongmocdct.com.vn/noi-that-phong-ngu/tap-dau-giuong-btdct07',
    'https://xuongmocdct.com.vn/noi-that-phong-ngu/tap-dau-giuong-btdct02',
]
for i in urls:
    res = requests.get(i)
    if res.status_code != 200:
        print(res.url)